// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("")]
[assembly: AssemblyCopyrightAttribute("Copyright Dave Timmins (c) 2013")]
[assembly: AssemblyProductAttribute("ArcGIS REST API ServiceModel PCL")]
[assembly: AssemblyVersionAttribute("5.1.0")]
[assembly: AssemblyFileVersionAttribute("5.1.0")]
[assembly: AssemblyInformationalVersionAttribute("5.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "5.1.0";
    }
}
