// <auto-generated/>
using System;
using System.Reflection;

[assembly: AssemblyCompanyAttribute("")]
[assembly: AssemblyCopyrightAttribute("Copyright Dave Timmins (c) 2013")]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyProductAttribute("ArcGIS REST API ServiceModel PCL")]
[assembly: AssemblyVersionAttribute("5.0.1")]
[assembly: AssemblyFileVersionAttribute("5.0.1")]
[assembly: AssemblyInformationalVersionAttribute("5.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "5.0.1";
    }
}
