require "rake/clean"

CLEAN.include "*.xam"
CLEAN.include "xamarin-component"

COMPONENT = "ArcGIS.PCL-4.0.0-beta2.xam"

file "xamarin-component/xamarin-component.exe" do
	puts "* Downloading xamarin-component..."
	mkdir "xamarin-component"
	sh "curl -L https://components.xamarin.com/submit/xpkg > xamarin-component.zip"
	sh "unzip -o -q xamarin-component.zip -d xamarin-component"
	sh "rm xamarin-component.zip"
end

task :default => "xamarin-component/xamarin-component.exe" do
	line = <<-END
	mono xamarin-component/xamarin-component.exe create-manually #{COMPONENT} \
		--name="ArcGIS.PCL" \
		--summary="Use ArcGIS Server REST types and resources without an official SDK. Also supports converting GeoJSON to and from ArcGIS Features." \
		--publisher="Dave Timmins" \
		--website="https://github.com/davetimmins/ArcGIS.PCL" \
		--details="Details.md" \
		--license="License.md" \
		--getting-started="GettingStarted.md" \
		--icon="icons/ArcGIS.PCL_128x128.png" \
		--icon="icons/ArcGIS.PCL_512x512.png" \
		--library="ios":"../lib/MonoTouch1/ArcGIS.ServiceModel.dll" \
		--library="ios":"../lib/MonoTouch1/ArcGIS.ServiceModel.Serializers.JsonDotNet.dll" \
		--library="ios":"../lib/MonoTouch1/ArcGIS.ServiceModel.iOS.dll" \
		--library="android":"../lib/MonoAndroid1/ArcGIS.ServiceModel.dll" \
		--library="android":"../lib/MonoAndroid1/ArcGIS.ServiceModel.Serializers.JsonDotNet.dll" \
		--library="android":"../lib/MonoAndroid1/ArcGIS.ServiceModel.Android.dll" \
		--sample="iOS Sample. Demonstrates calling a query and geocode ArcGIS Server service operation on iOS.":"../samples/ArcGIS.Portable.iOS/ArcGIS.Portable.iOS.sln" \
		--sample="Android Sample. Demonstrates calling a query and geocode ArcGIS Server service operation on Android":"../samples/ArcGIS.Portable.Android/ArcGIS.Portable.Android.sln"
		END
	puts "* Creating #{COMPONENT}..."
	puts line.strip.gsub "\t\t", "\\\n    "
	sh line, :verbose => false
	puts "* Created #{COMPONENT}"
end
